### ISSUE TITLE
Please add channel(s)

### ISSUE THREAD

**Issue by Hybson** [miscavage/De-Mainstream-YouTube-Extension#1]
CBS Boston - https://www.youtube.com/user/CBSBostonWBZ
CBS Miami - https://www.youtube.com/user/CBSMiami
ABC News - https://www.youtube.com/user/ABCNews
Wall Street Journal - https://www.youtube.com/user/WSJDigitalNetwork
NPR - https://www.youtube.com/user/npr
The View - https://www.youtube.com/user/ABCTheView
NBC New York - https://www.youtube.com/user/WNBC4NewYork
CBS Dallas Forth Worth - https://www.youtube.com/user/CBSDFW
The Ellen SHow - https://www.youtube.com/user/TheEllenShow
CBS Los Angeles - https://www.youtube.com/user/1cbsla
MSNBC - https://www.youtube.com/user/msnbcleanforward
The Hill - https://www.youtube.com/channel/UCPWXiRWZ29zrxPFIQT7eHSA
WMUR-TV - https://www.youtube.com/user/wmurtv
Click On Detroit - https://www.youtube.com/channel/UCqMdEOPBZbGPykVOhUqWqfA
Washington Post - https://www.youtube.com/user/WashingtonPost
Los Angeles Times - https://www.youtube.com/user/losangelestimes
POLITICO - https://www.youtube.com/user/thepolitico
KPIX CBS SF Area - https://www.youtube.com/user/CBSSanFrancisco
The Young Turks - https://www.youtube.com/user/TheYoungTurks
Washington Week - https://www.youtube.com/user/washingtonweekGI
Fox Nation - https://www.youtube.com/channel/UCG1CoynVOh5uj12qpDLQ7fQ
Full Frontal W/ Sam Bee - https://www.youtube.com/channel/UC18vz5hUUqxbGvym9ghtX_w
Fox 10 Phoenix - https://www.youtube.com/channel/UCJg9wBPyKMNA5sRDnvzmkdg
Fox 5 Atlanta - https://www.youtube.com/channel/UCjHWv2DU5-HLpogAAr386DQ

**Comment by kazz-trismus** [comment]
please just add all the top 20 channels constantly on trending page and/or a custom link input.
https://www.youtube.com/user/XXXXXXXXXXXX

**Comment by lbralasconnect** [comment]
The Young Turks are youtubers.

**Comment by miscavage** [comment]
will add them all but the young turks. specifically because they are not what i consider "mainstream"... i consider "mainstream" anything on tv. however, in a later version i will add the ability for people to add custom channels to a block list

**Comment by boson961** [comment]
@miscavage You have done a great service by creating this extension. If you add the ability to customise our own blocklists, that would be awesome.

**Comment by miscavage** [comment]
added channels: 2be93ff closing this issue
