### ISSUE TITLE
UK & Other Mainstream Channels to be Added.

### ISSUE THREAD

**Issue by RootCookie** [miscavage/De-Mainstream-YouTube-Extension#11]
https://www.youtube.com/user/EveningStandardNews
https://www.youtube.com/user/BBCNewsnight
https://www.youtube.com/user/ITVNews
https://www.youtube.com/user/Channel4News
https://www.youtube.com/user/thismorning

https://www.youtube.com/channel/UC9GGzAhhvhJO1hL10-BcgNA
https://www.youtube.com/channel/UCBte7YLdJx-O_YljuvN6whg
https://www.youtube.com/user/CBCTheNational
https://www.youtube.com/user/WSJDigitalNetwork
https://www.youtube.com/channel/UChirEOpgFCupRAk5etXqPaA
https://www.youtube.com/channel/UCIALMKvObZNtJ6AmdCLP7Lg
https://www.youtube.com/user/channelnewsasia
https://www.youtube.com/user/france24
https://www.youtube.com/user/deutschewelleenglish
https://www.youtube.com/user/kenyacitizentv

**Comment by miscavage** [comment]
ok

**Comment by webchris** [comment]
Please add some Swedish channels:
https://www.youtube.com/channel/UC7QxZdogxV1gloaOBO02wiw
https://www.youtube.com/user/ExpressenTV
https://www.youtube.com/user/dn
https://www.youtube.com/user/SVT
https://www.youtube.com/user/AllehandaMedia
https://www.youtube.com/user/GoteborgsPosten

**Comment by breeze88** [comment]
https://www.youtube.com/channel/UCeqKIgPQfNInOswGRWt48kQ

**Comment by miscavage** [comment]
added in v1.0.4 that is now live on chrome, firefox: https://twitter.com/MarkMiscavage/status/1229431420403306496
