### ISSUE TITLE
Add "The View" mainstream and very nasty

### ISSUE THREAD

**Issue by gtcrypto** [miscavage/De-Mainstream-YouTube-Extension#12]
{   "id": "ABCTheView/featured",   "name": "The View",   "icon": "../img/channels/the-view.jpg" },

There are all these channels that still pop up which renders the "search" function still unworkable.
"The View" is just one of example. Search something like "Biden"and see how many still pop up.

**Comment by miscavage** [comment]
added in latest version that is live now on firefox, chrome: https://twitter.com/MarkMiscavage/status/1229431420403306496
