### ISSUE TITLE
Block list sharing

### ISSUE THREAD

**Issue by ReNardier** [miscavage/De-Mainstream-YouTube-Extension#16]
an easy way for people to share their custom block lists though plain text

**Comment by miscavage** [comment]
good idea. will think about ways to implement.

**Comment by registerthis** [comment]
This and making the list editable in a config file so those without right click functionality can still block new sites they want blocked.

**Comment by miscavage** [comment]
added ability to add in new channels via comma-separated list or individually by entering channel name and/or channel id in version 1.0.5
