### ISSUE TITLE
Got Talent Global not blocked

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [miscavage/De-Mainstream-YouTube-Extension#17]
Although the extension does what it does and well, some channels are getting around this by making alternate channels.  An example of this is a channel called Got Talent Global which seems to be getting around the blocking of the America's Got Talent channel:

https://www.youtube.com/user/gottalentglobal

There's these channels which aren't affiliated with America's Got Talent but still host their content:

https://www.youtube.com/channel/UCeBWh-0p7vgBeD6HOHBpfwQ

https://www.youtube.com/channel/UCSWwb_YyNB8vuC1VDcfPPaQ

https://www.youtube.com/user/AmazingSingles

https://www.youtube.com/channel/UCMl6pPuV-d12pbgV5Ugugjw

And even after that, there's dozen of other channels with "got talent" in the channel name that host videos about America's Got Talent.  This extension seems to be looking for channel names, not video titles, and that's where channels can get around its detection system.

**Comment by miscavage** [comment]
have added gottalentglobal in the latest version 1.0.5
also, i've added ability to add in new channels via comma-seperated list or individually by entering channel name and/or channel id
