### ISSUE TITLE
Extension not working with old youtube layout

### ISSUE THREAD

**Issue by DiseaseG** [miscavage/De-Mainstream-YouTube-Extension#2]
So I am using a script named "YouTube Polymer Disable" that lets me use the old youtube layout. Because of this the De-mainstream extension does not work. Is a fix possible?

This is the script if you want to see it.

> // ==UserScript==
> // @name YouTube Polymer Disable
> // @match *://www.youtube.com/*
> // @exclude *://www.youtube.com/embed/*
> // @grant none
> // @run-at document-start
> // ==/UserScript==
> var url = window.location.href;
> if (url.indexOf("disable_polymer") === -1) {
>   if (url.indexOf("?") > 0) {
>     url += "&";
>   } else {
>     url += "?";
>   }
>   url += "disable_polymer=1";
>   window.location.href = url;
> }

**Comment by miscavage** [comment]
this extension is made to work only for the new youtube layout and i cannot work around other extensions/scripts from third parties to make this extension work
