### ISSUE TITLE
Rotten Tomatoes

### ISSUE THREAD

**Issue by dwetuski** [miscavage/De-Mainstream-YouTube-Extension#21]
Rotten Tomatoes is a propaganda website with ties to Disney that manipulates their reviews and ratings to try to make Disney films in particular appear more favorable, but none of their information is trustworthy.  R.T. YouTube videos are also quite heavily promoted and are often recommended to anyone with an interest in movie news, even if they try to avoid clicking on R.T. videos and then click dislike whenever a R.T. video is clicked accidentally.

**Comment by miscavage** [comment]
added rotten tomatoes to block list in version 1.0.5
