### ISSUE TITLE
Remove "important" from inline style declarations for daily top link

### ISSUE THREAD

**Issue by RevanProdigalKnight** [miscavage/De-Mainstream-YouTube-Extension#23]
The link that is inserted for the daily top videos has inline styles declared on every element it creates and every one of the inline style rules has an `!important` modifier. This makes it impossible for custom themes to affect the link. Please remove the `!important` modifier from all inline CSS.

**Comment by miscavage** [comment]
good point. removed and updated in version 1.0.5
