### ISSUE TITLE
Brazilian and Portuguese channels

### ISSUE THREAD

**Issue by gabriellluz** [miscavage/De-Mainstream-YouTube-Extension#26]
Hi.

I'd like to point these channels below to be blocked:

Brazili:
https://www.youtube.com/user/vejapontocom

Portugal:
https://www.youtube.com/user/euronewspt

USA:
https://www.youtube.com/user/HBO
https://www.youtube.com/user/CNBCInternational
https://www.youtube.com/user/NewsyHub
https://www.youtube.com/user/france24english
https://www.youtube.com/user/EWTN
https://www.youtube.com/user/TheYoungTurks/videos
https://www.youtube.com/channel/UCV61VqLMr2eIhH4f51PV0gA/videos (BloombergPolitics)
https://www.youtube.com/channel/UCaeO5vkdj5xOQHp4UmIN6dw/videos (The Daily Wire)

More latin and spanish channels:
https://www.youtube.com/user/canalNTN24

**Comment by miscavage** [comment]
added in latest version 1.0.5
