### ISSUE TITLE
Good Morning America

### ISSUE THREAD

**Issue by Reezlaw** [miscavage/De-Mainstream-YouTube-Extension#27]
It's annoying to see this in my search results. Verified checkmark and all. would love to get rid of it.

https://www.youtube.com/channel/UCH1oRy1dINbMVp3UFWrKP0w

**Comment by miscavage** [comment]
added in newest version 1.0.5

**Comment by Reezlaw** [comment]
Awesome ☺️

Il sab 28 mar 2020, 23:54 Mark Miscavage <notifications@github.com> ha
scritto:
