### ISSUE TITLE
Channels to add

### ISSUE THREAD

**Issue by OpenBSD-Neurotik** [miscavage/De-Mainstream-YouTube-Extension#3]
“News”:

Arirang News - https://www.youtube.com/user/arirangnews
SABC Digital News - https://www.youtube.com/user/sabcdigitalnews
SABC Iindaba - https://www.youtube.com/channel/UCl8gMaUWyG6v9gxpq6iWbmA
SABC Izindaba - https://www.youtube.com/channel/UCSO8qij295DSxMiofTLk9QQ
The Lallantop - https://www.youtube.com/channel/UCx8Z14PpntdaxCt2hakbQLQ
India Today - https://www.youtube.com/channel/UCYPvAwZP8pZhSMW8qs7cVCw
1Mg - https://www.youtube.com/channel/UCNUvsEya-Jq_Pw1t6R47hew
South China Morning Post - https://www.youtube.com/user/scmp888
CNA - https://www.youtube.com/user/channelnewsasia
NTDTV - https://www.youtube.com/user/NTDTV
Hindustan Times - https://www.youtube.com/user/ht
CGTN - https://www.youtube.com/user/CCTVNEWSbeijing
CGTN Live - https://www.youtube.com/channel/UCviqjOZN3ZvDEmZfHuUKCIQ
CGTN America - https://www.youtube.com/user/CCTVAmerica1
CGTN Africa - https://www.youtube.com/user/CCTVAFRICALIVE
CGTN en Español - https://www.youtube.com/channel/UCd94YCD7yp6d-YZSRYWyeFA
CGTN Français - https://www.youtube.com/user/CCTVFrench
CGTN Arabic - https://www.youtube.com/channel/UCQmJk0ErE_FiorcLBsDKORA
CGTN на русском - https://www.youtube.com/channel/UCA2WHG4EpVqul3TYjAF0k2A
CCTV Video News Agency - https://www.youtube.com/channel/UCmv5DbNpxH8X2eQxJBqEjKQ
CCTV Faces Of Africa - https://www.youtube.com/user/CCTVFacesOfAfrica
CCTV Talk Africa - https://www.youtube.com/user/CCTVTalkAfrica
ABS-CBN News - https://www.youtube.com/user/TheABSCBNNews
ANC 24/7 - https://www.youtube.com/user/ANCalerts
The Star Online - https://www.youtube.com/user/thestaronline
Former Malaysian MSM newspaper now pushing online video news

Canada "news"
CBC News: The National - https://www.youtube.com/user/CBCTheNational
CBC Kids - https://www.youtube.com/user/kidscbc
CBC Kids News - https://www.youtube.com/channel/UCWUA2W6LueNy9BSovivFVvQ
CBC Parents - https://www.youtube.com/channel/UCBsb3Xi9nBp0LFQ7zVtAoHA
CBC Sports - https://www.youtube.com/user/CBCSports
CBC Arts - https://www.youtube.com/channel/UCbExnsDIg9qnktUKtKbZ7dQ
Radio Canada - https://www.youtube.com/user/RadioCanada
CBC NL - Newfoundland and Labrador - https://www.youtube.com/channel/UCpPLxYC6uNNfNrSQokButSg
CBC Nova Scotia - https://www.youtube.com/user/cbcns
CBC Vancouver - https://www.youtube.com/channel/UCiKE6mqbKmGGlNAtccn04MA

US "news"
QuickTake by Bloomberg - https://www.youtube.com/channel/UChirEOpgFCupRAk5etXqPaA
Barcroft TV - https://www.youtube.com/user/barcroftmedia

England/Europe "news"
ITV News - https://www.youtube.com/user/ITVNews
DW Nel 4 - https://www.youtube.com/user/channel4
On Demand News - https://www.youtube.com/user/itnnews
The Guardian - https://www.youtube.com/user/TheGuardian
The Guardian News - https://www.youtube.com/user/guardianwires
Euronews - https://www.youtube.com/user/Euronews

other:
ABC News (Australia) - https://www.youtube.com/user/NewsOnABC

MSM affiliated garbage that YT keeps pushing in recommended, search or sidebars
On Demand Entertainment - https://www.youtube.com/user/itn
All 4 - https://www.youtube.com/channel/UCiZ47iCEOmqsyZU_6XP9ekg
Made in Chelsea - https://www.youtube.com/user/e4madeinchelsea
Chattymanc - https://www.youtube.com/user/chattymanc4
Celebs Go Dating - https://www.youtube.com/channel/UC5U68CWHSX5CgJM2P1d9rhg
Hollyoaks - https://www.youtube.com/user/hollyoaks
E4 - https://www.youtube.com/user/e4
Mashed - https://www.youtube.com/user/mashed
4Music - https://www.youtube.com/user/TheOfficial4Music
Channel 4 Documentary - https://www.youtube.com/channel/UCooTDp-fERMGRHIQ4VL4qlg
Channel 4 Sport - https://www.youtube.com/user/Channel4Racing
Channel 4 Comedy - https://www.youtube.com/user/Comedyon4
Film4 - https://www.youtube.com/user/Film4video
Random Acts - https://www.youtube.com/channel/UCWwZGGoPLUfZmhm5zwKGHbg
Unreported World - https://www.youtube.com/channel/UClz-d22g9Lj7agZSbaRKuqA
This Is Genius - https://www.youtube.com/user/ITNExtreme

Guardian network:
Guardian Football - https://www.youtube.com/user/GuardianFootball
Guardian Sport - https://www.youtube.com/channel/UCwD9E_QNwFwrQC7OnPnrg2Q
Guardian Culture - https://www.youtube.com/user/GuardianCultureArts
Guardian Jobs - https://www.youtube.com/user/guardianjobs
Owen Jones - https://www.youtube.com/channel/UCSYCo8uRGF39qDCxF870K5Q
The guardian puppet, not a ytber
The Royal Family Channel - https://www.youtube.com/user/royalweddingchannel
The Royal Fashion Channel - https://www.youtube.com/user/Fashion411
Point - https://www.youtube.com/user/truthloader 
Guardian Supporters - https://www.youtube.com/user/guardianmembership
Game on - https://www.youtube.com/user/gameon
The Music 411 - https://www.youtube.com/user/itnmusic
Sports News - https://www.youtube.com/user/ITNSportsNews

**Comment by meunke** [comment]
Please also add:
CBS This Morning - https://www.youtube.com/user/CBSThisMorning
NBC News - https://www.youtube.com/user/NBCNews

**Comment by MewingLullaby** [comment]
More MSM friendlies / boosted trash

SaturdayNightLive - https://www.youtube.com/user/SaturdayNightLive 
AmericasGotTalent - https://www.youtube.com/user/AmericasGotTalent

**Comment by meunke** [comment]
Bloomberg Politics - https://www.youtube.com/channel/UCV61VqLMr2eIhH4f51PV0gA

**Comment by rejewtech** [comment]
Please also add:
The Hill - https://www.youtube.com/channel/UCPWXiRWZ29zrxPFIQT7eHSA
Good Morning Britain - https://www.youtube.com/user/GMB
Wall Street Journal - https://www.youtube.com/user/WSJDigitalNetwork
Saturday Night Live - https://www.youtube.com/user/SaturdayNightLive
Team Coco - https://www.youtube.com/user/teamcoco
The View - https://www.youtube.com/user/ABCTheView
The Ellen Show - https://www.youtube.com/user/TheEllenShow
Linus Tech Tips - https://www.youtube.com/user/LinusTechTips

**Comment by DiseaseG** [comment]
Why Linus tech Tips? Dude is literally a youtuber that made it. Why would you punish success?

**Comment by mantrasNire** [comment]
Thank you very much for this addon.  It is fantastic!
Some more channels - 

Yahoo Finance - https://www.youtube.com/channel/UCEAZeUIeJs0IjQiqTCdVSIg
The Star Online - https://www.youtube.com/user/thestaronline/featured
Reuters - https://www.youtube.com/user/ReutersVideo

**Comment by snow-frog** [comment]
Channel 4 News https://www.youtube.com/user/Channel4News
DW Deutsch https://www.youtube.com/user/deutschewelle
DW Espanol https://www.youtube.com/user/DeutscheWelleEspanol
VOA News https://www.youtube.com/user/VOAvideo
WION https://www.youtube.com/channel/UC_gUM8rL-Lrg6O3adPW9K1g
Aj Jojo Vivo https://www.youtube.com/channel/UCDUxOvbwu1bnyD7AucP0ESw

**Comment by NeutronCactus** [comment]
@miscavage Do you accept pull requests?

The channels list doesn't have to be sorted by name, correct?

For channels from various countries would you prefer to keep all of them sorted by name or to divide them into sections one for each country? E.g. artificially with a comment.

Currently the images of channels are released with the extension. This makes the addition of new channels more tiresome. What is your opinion about replacing that with some other mechanism, e.g. downloading all of the images from YT directly into some local storage. Is releasing the logos of these MSM outlets legal?

If more channels are added, from various countries, the channels list will become long and at some point the UI will have to modified, e.g. categorized by country, etc. If you have an idea about it already please share so if additional metadata are needed on the channels list we can add it from the beginning so you have the data to work with.

**Comment by NeutronCactus** [comment]
The fact that you don't like certain people/channels like Owen Jones or Linus Tech Tips doesn't mean they are the MSM. A YouTuber may be a "puppet" if he/she chooses to be.

@miscavage have you thought about a clear definition of what qualifies as an MSM channel to be included in the extension in order to avoid arguments about opinions?

**Comment by pdoggeth** [comment]
I think to be very versatile, there should be a way for the user to simply add any channel they don't want to see on the list.

**Comment by foemerson** [comment]
You should also add ABC: https://www.youtube.com/user/ABCNetwork

**Comment by a-war-of-gifts** [comment]
Thank-you so much for this plugin. I have been looking for something like this for months! I have 5 years of experience in software development. If you ever need someone to assist with developing and maintaining this project, please don't hesitate to ask me. Long term, it makes a lot of sense to just let users add their own custom lists. I would be happy to help with developing that feature.

Please remove
Bloomberg Markets and Finance
Yahoo Finance
CNBC International TV

**Comment by alexandereliott** [comment]
Can we also include corporate owned entertainment media?

**Comment by saturnotaku** [comment]
How about the major professional sports leagues - NBA, NFL, MLB, NHL?

**Comment by alexandereliott** [comment]
please add sun newspaper.
https://www.youtube.com/user/thesunnewspaper

**Comment by miscavage** [comment]
> The fact that you don't like certain people/channels like Owen Jones or Linus Tech Tips doesn't mean they are the MSM. A YouTuber may be a "puppet" if he/she chooses to be.
> 
> @miscavage have you thought about a clear definition of what qualifies as an MSM channel to be included in the extension in order to avoid arguments about opinions?

yes, a channel will qualify as MSM if they are on TV. very simple

**Comment by miscavage** [comment]
working on adding most of the recommended channels in this issue at the moment. as well as putting in ability to add custom channels as you wish

**Comment by ar-li1** [comment]
> channel will qualify as MSM if they are on TV
What if a media entity has more than one Youtube channel? For example, I am now compiling a list of Russian state-funded media and the likes of Sputnik and RT have **dozens** of channels, but not all of these sub-entites appear on TV separately. What is the approach in this situation?

**Comment by miscavage** [comment]
added channels that you all have posted with some exceptions in latest commit: 2be93ff
for new questions, issues, comments, please open a new issue. closing this one now
