### ISSUE TITLE
Still getting blacklisted search results

### ISSUE THREAD

**Issue by Steve-just-steve** [miscavage/De-Mainstream-YouTube-Extension#5]
When searching for current popular news term I still get results from blacklisted channels

**Comment by miscavage** [comment]
can you be more specific as to what results you are getting? like what channel is showing up that is not supposed to be there?

**Comment by miscavage** [comment]
@Steve-just-steve i've just updated the extension to v1.0.4 - can you please confirm if you are still experiencing these issues?

**Comment by miscavage** [comment]
Closing

**Comment by Steve-just-steve** [comment]
Sorry about that I accidentally unsubbed for notifications. Yes that fixed it. Very sorry about that
